# source https://github.com/apache/pulsar/blob/master/docker-compose/standalone-dashboard/docker-compose.yml
version: '3'

services:

  standalone:
    image: apachepulsar/pulsar
    expose:
      - 8080
      - 6650
    ports:
      - '6650:6650'
    environment:
      - BOOKIE_MEM=" -Xms512m -Xmx512m -XX:MaxDirectMemorySize=1g"
    command: >
      /bin/bash -c
      "bin/apply-config-from-env.py conf/standalone.conf
      && bin/pulsar standalone --advertised-address standalone"
    volumes:
      - pulsardata:/pulsar/data
      - pulsarconf:/pulsar/conf
  dashboard:
    image: apachepulsar/pulsar-dashboard
    depends_on:
      - standalone
    ports:
      - '8081:80'
    environment:
      - SERVICE_URL=http://standalone:8080
  manager:
    image: apachepulsar/pulsar-manager
    expose:
      - 9527
      - 7750
    ports:
      - '9527:9527'
      - '7750:7750'
    environment:
      - SPRING_CONFIGURATION_FILE=/pulsar-manager/pulsar-manager/application.properties

volumes:
  pulsardata:
  pulsarconf:
